title: Infinite, Worthless Time
url: "https://cedeless.com"
author: Reuben Dalke

collections:
  posts:
    output: true
    permalink: /iwt/:categories/:year/:month/:day/:title/
    
paginate: 20
paginate_path: "/iwt/page:num/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  
feed:
  path: /iwt/feed.xml
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
